using Demo.Contracts;
using System;
using System.Collections.Generic;
using System.Threading;

namespace Demo.Wcf
{
    public class LrpManager : ILrp
    {
        private List<int> list = new List<int>();

        public void StartProcess()
        {
            var rnd = new Random(100000);
            for (var i = 0; i < 100; i++)
            {
                var gen = rnd.Next();
                this.list.Add(gen);

                Console.WriteLine("Generated by the service: {0}", gen);
                Thread.Sleep(1500);
            }
        }
    }
}
